#! /bin/bash

# GENERIC ROS2 LAUNCHER FOR gazebo-classic-sitl.
# ALWAYS STARTS THE uXRCE-DDS AGENT, THEN RUNS THE APP SELECTED BY ${ROS2_APP}
# (scripts/ros2/apps/<ROS2_APP>.sh). DO NOT EDIT THIS FILE TO ADD APPS -
# JUST DROP A NEW scripts/ros2/apps/<name>.sh AND SET ROS2_APP=<name> IN envs/ros2.env.

# INITIAL STATEMENTS
# >>>----------------------------------------------------

# SET THE BASIC ENVIRONMENT VARIABLE
export TERM=xterm-256color

# SET THE BASE DIRECTORY
BASE_DIR=$(dirname $(readlink -f "$0"))
WORKSPACE_DIR=$(dirname $(dirname $(readlink -f "$0")))

# SOURCE THE ENVIRONMENT AND FUNCTION DEFINITIONS
for file in ${BASE_DIR}/include/*.sh; do
    source ${file}
done
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


# MAIN STATEMENTS
# >>>----------------------------------------------------

source ${BASE_DIR}/sourceAll.sh

CheckFileExists ${BASE_DIR}/uxrce-dds.sh
CheckFileExecutable ${BASE_DIR}/uxrce-dds.sh

# CREATE DIRECTORY FOR LOGS
CheckDirExists ${WORKSPACE_DIR}/logs create
rm -rf ${WORKSPACE_DIR}/logs/*

# ALWAYS RUN THE uXRCE-DDS AGENT (BRIDGES PX4 uORB <-> ROS2 DDS)
touch ${WORKSPACE_DIR}/logs/uxrce-dds.log
${BASE_DIR}/uxrce-dds.sh 2>&1 | tee ${WORKSPACE_DIR}/logs/uxrce-dds.log &

# STAGE 1: WAIT UNTIL THE uXRCE-DDS AGENT HAS BRIDGED PX4 (/fmu TOPICS PRESENT).
EchoYellow "[$(basename "$0")] WAITING FOR uXRCE-DDS AGENT + PX4 (/fmu TOPICS)..."
agent_ready=0
for _i in $(seq 1 60); do
    if ros2 topic list 2>/dev/null | grep -q "^/fmu/"; then
        agent_ready=1
        break
    fi
    sleep 1
done
if [ "${agent_ready}" -eq 1 ]; then
    EchoGreen "[$(basename "$0")] /fmu TOPICS AVAILABLE - PX4 BRIDGED."
else
    EchoRed "[$(basename "$0")] TIMEOUT WAITING FOR /fmu TOPICS."
fi

# STAGE 2: WAIT UNTIL PX4 IS READY FOR TAKEOFF (pre-arm checks pass), so the app does
# NOT command arm/offboard before EKF/GPS have converged ("Ready for takeoff").
EchoYellow "[$(basename "$0")] WAITING FOR PX4 TO BE READY FOR TAKEOFF..."
px4_ready=0
for _i in $(seq 1 120); do
    if timeout 3 ros2 topic echo --once /fmu/out/vehicle_status_v1 2>/dev/null | grep -q "pre_flight_checks_pass: true"; then
        px4_ready=1
        break
    fi
    sleep 1
done
if [ "${px4_ready}" -eq 1 ]; then
    EchoGreen "[$(basename "$0")] PX4 READY FOR TAKEOFF - STARTING APP."
else
    EchoRed "[$(basename "$0")] TIMEOUT WAITING FOR PX4 READY - STARTING APP ANYWAY."
fi

# RUN THE SELECTED ROS2 APP (DROP-IN: scripts/ros2/apps/<ROS2_APP>.sh)
export WORKSPACE_DIR BASE_DIR
APP_SCRIPT=${BASE_DIR}/apps/${ROS2_APP}.sh
if [ -n "${ROS2_APP}" ] && [ -x "${APP_SCRIPT}" ]; then
    EchoGreen "[$(basename "$0")] RUNNING ROS2 APP: ${ROS2_APP}"
    touch ${WORKSPACE_DIR}/logs/${ROS2_APP}.log
    ${APP_SCRIPT} 2>&1 | tee ${WORKSPACE_DIR}/logs/${ROS2_APP}.log &
elif [ -n "${ROS2_APP}" ]; then
    EchoRed "[$(basename "$0")] ROS2_APP='${ROS2_APP}' BUT ${APP_SCRIPT} NOT FOUND/EXECUTABLE. IDLING."
else
    EchoYellow "[$(basename "$0")] ROS2_APP IS EMPTY. RUNNING AGENT ONLY (IDLE)."
    EchoYellow "[$(basename "$0")] SET ROS2_APP=<name> IN envs/ros2.env AND ADD scripts/ros2/apps/<name>.sh"
fi

sleep infinity

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
